image: Visual Studio 2017
platform: x64
configuration: Release

# clone directory
clone_folder: c:\projects\saturn

install:
    - cmd: set PATH=C:\Program Files\Git\cmd;C:\cygwin64\bin;C:\Program Files (x86)\CMake\bin;C:\Windows\System32;C:\Windows\System32\wbem

    # Python
    - cmd: curl https://www.python.org/ftp/python/2.7.13/python-2.7.13.amd64.msi -o python.msi
    - cmd: msiexec /a python.msi /qb TARGETDIR=C:\projects\saturn\python

    # GNU ed
    - cmd: curl ftp://cygwin.osuosl.org/pub/cygwin/x86_64/release/ed/ed-1.14.1-1.tar.xz -o ed.tar.xz
    - cmd: tar -xf ed.tar.xz

    # unzip
    - cmd: curl ftp://cygwin.osuosl.org/pub/cygwin/x86_64/release/unzip/unzip-6.0-17.tar.xz -o unzip.tar.xz
    - cmd: tar -xf unzip.tar.xz

    # jom
    - cmd: curl --tlsv1.2 -o jom.tar.xz -L https://github.com/VictorYudin/saturn-jom/releases/download/1.0.5/jom-v1.1.2.tar.xz
    - cmd: tar -xf jom.tar.xz

    # Put them to PATH
    - cmd: set PATH=%PATH%;C:\projects\saturn\usr\bin;C:\projects\saturn\jom\bin

    # MSVC environment
    - cmd: '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"'

    - cmd: git clone https://github.com/VictorYudin/saturn.git

build_script:
    - cmd: make -C saturn PYTHON_BIN=C:/projects/saturn/python/python.exe llvm-archive -j4

artifacts:
    - path: saturn/*.tar.xz
      name: Package

deploy:
    - provider: Environment
      name: GitHub Release

only_commits:
    message: /build/
